### ISSUE TITLE
Give option to add some label text on first step

### ISSUE THREAD

**Issue by saqueib** [dai-siki/vue-image-crop-upload#34]
Thanks for really beautiful and complete image crop uploader, If you can add a `<slot>` where we can add some text on the first step it will be great, currently it says nothing only a upload area. I wanted to add some text on the first step. like **Please upload an image no more than 1 MB**.

**Comment by dai-siki** [comment]
![image](https://user-images.githubusercontent.com/18674462/27265631-20a5c96c-54cb-11e7-978c-3de6aa6b9be7.png)
The picture is the default prompt on the first step. If you see nothing, perhaps because the global box "box-sizing: border-box;"; I have made adjustments and updated the version @1.3.13;  If you want to modify the prompts, you can set the "lang-ext " property

**Comment by saqueib** [comment]
@dai-siki Still not showing the `hint` text, your last commit you only changed the version in packages.json not any other file, what needs to be changed in order to show the hint text, I am using Bootstrap 4 and text is not visible, please help

**Comment by dai-siki** [comment]
![fkaz538 _ 5ovf4r g2 55d](https://user-images.githubusercontent.com/18674462/27761865-1181d9f4-5e98-11e7-854f-d744ce2db1bb.png)
Should it be good, can you take this part of the screenshot of the debugging to me?

**Comment by saqueib** [comment]
Here is screenshot you asked

![screen shot 2017-07-01 at 6 39 28 pm](https://user-images.githubusercontent.com/6937224/27762290-04a0c9a8-5e8d-11e7-92d8-fad8a87d2717.png)

**Comment by dai-siki** [comment]
You update the next version @1.3.13, it should be no problem
